# Generated by Django 2.2.7 on 2020-02-06 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0007_merge_20180419_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
